version: 0.2
phases:
  pre_build:
    commands:
      - echo Using tooling dotnet version `dotnet --version`
      - echo Restore started on `date`
      - dotnet restore PostgreSQLTest/PostgreSQLTest.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release -o ./build_output PostgreSQLTest/PostgreSQLTest.csproj
artifacts:
  files:
    - PostgreSQLTest/build_output/**/*
    - scripts/**/*
 