version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-2 --no-include-email)
      - REPOSITORY_URI=xxxxxxxxxxxx.dkr.ecr.us-east-2.amazonaws.com/aspnet
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t postgresqltest .
      - docker tag postgresqltest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
 
